#ifndef TEST_M68K_H
#define TEST_M68K_H

void test_initialization();
void test_register_access();
void test_memory_access();
void test_fetch();
void test_move();
void test_arithmetic();
void test_control_flow();
void test_logic();
void test_data_manipulation();
void test_shift_rotate();
void test_cmp_tst();
void test_exceptions();
void test_lea_pea();
void test_stack_frame();
void test_dbcc_scc();
void test_addressing_mode_6();
void test_exg();
void test_adda_suba();
void test_addx_subx();
void test_pcrel();
void test_movem();
void test_bcd();
void test_misc_control();
void test_interrupts();
void test_regression_postinc_predec_byte();
void test_regression_reset_vectors();
void test_regression_jmp_dispatch();
void test_regression_div_by_zero();
void test_regression_addx_subx_zflag();
void test_regression_sbcd();
void test_regression_nbcd();
void test_regression_stop_privilege();
void test_regression_ext_dispatch();
void test_bit_manipulation();
void test_immediate_alu();
void test_negx();
void test_new_tas();
void test_movep();
void test_usp_switching();
void test_address_error();
void test_trace_mode();
void test_stopped_state();
void test_fibonacci();
void test_string_copy();
void test_exception_handler();

#endif
