[project]
name = "rocket68"
version = "0.1.0"
description = "The Python environment for the Rocket 68 project"

requires-python = ">=3.10,<4.0"
dependencies = [
  "pre-commit >=4.2.0",
  "mkdocs >=1.6.1",
  "mkdocs-material >=9.6.12",
  "mkdocstrings-python >=1.16.10",
  "pyyaml == 6.0.3", # For MkDocs compatibility
  "clang-format>=22.1.8",
]
