name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make doxygen python3-pip
          pip3 install uv
          uv sync

      - name: Generate Documentation
        run:  |
          source .venv/bin/activate
          make docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          user_name: ${{ github.actor }}
          user_email: ${{ github.actor }}@users.noreply.github.com
          commit_message: "docs: Deploy documentation from ${{ github.sha }} by ${{ github.actor }}"
